// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package opampmock

import (
	"context"

	"github.com/open-telemetry/opamp-go/server/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionManager creates a new instance of MockConnectionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionManager {
	mock := &MockConnectionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionManager is an autogenerated mock type for the ConnectionManager type
type MockConnectionManager struct {
	mock.Mock
}

type MockConnectionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionManager) EXPECT() *MockConnectionManager_Expecter {
	return &MockConnectionManager_Expecter{mock: &_m.Mock}
}

// AddConnection provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) AddConnection(conn types.Connection, id string) {
	_mock.Called(conn, id)
	return
}

// MockConnectionManager_AddConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConnection'
type MockConnectionManager_AddConnection_Call struct {
	*mock.Call
}

// AddConnection is a helper method to define mock.On call
//   - conn types.Connection
//   - id string
func (_e *MockConnectionManager_Expecter) AddConnection(conn interface{}, id interface{}) *MockConnectionManager_AddConnection_Call {
	return &MockConnectionManager_AddConnection_Call{Call: _e.mock.On("AddConnection", conn, id)}
}

func (_c *MockConnectionManager_AddConnection_Call) Run(run func(conn types.Connection, id string)) *MockConnectionManager_AddConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Connection
		if args[0] != nil {
			arg0 = args[0].(types.Connection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionManager_AddConnection_Call) Return() *MockConnectionManager_AddConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_AddConnection_Call) RunAndReturn(run func(conn types.Connection, id string)) *MockConnectionManager_AddConnection_Call {
	_c.Run(run)
	return _c
}

// DispatchRestartCommand provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) DispatchRestartCommand(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DispatchRestartCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionManager_DispatchRestartCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchRestartCommand'
type MockConnectionManager_DispatchRestartCommand_Call struct {
	*mock.Call
}

// DispatchRestartCommand is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnectionManager_Expecter) DispatchRestartCommand(ctx interface{}) *MockConnectionManager_DispatchRestartCommand_Call {
	return &MockConnectionManager_DispatchRestartCommand_Call{Call: _e.mock.On("DispatchRestartCommand", ctx)}
}

func (_c *MockConnectionManager_DispatchRestartCommand_Call) Run(run func(ctx context.Context)) *MockConnectionManager_DispatchRestartCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_DispatchRestartCommand_Call) Return(err error) *MockConnectionManager_DispatchRestartCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionManager_DispatchRestartCommand_Call) RunAndReturn(run func(ctx context.Context) error) *MockConnectionManager_DispatchRestartCommand_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveConnection provides a mock function for the type MockConnectionManager
func (_mock *MockConnectionManager) RemoveConnection(conn types.Connection) {
	_mock.Called(conn)
	return
}

// MockConnectionManager_RemoveConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveConnection'
type MockConnectionManager_RemoveConnection_Call struct {
	*mock.Call
}

// RemoveConnection is a helper method to define mock.On call
//   - conn types.Connection
func (_e *MockConnectionManager_Expecter) RemoveConnection(conn interface{}) *MockConnectionManager_RemoveConnection_Call {
	return &MockConnectionManager_RemoveConnection_Call{Call: _e.mock.On("RemoveConnection", conn)}
}

func (_c *MockConnectionManager_RemoveConnection_Call) Run(run func(conn types.Connection)) *MockConnectionManager_RemoveConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Connection
		if args[0] != nil {
			arg0 = args[0].(types.Connection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionManager_RemoveConnection_Call) Return() *MockConnectionManager_RemoveConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnectionManager_RemoveConnection_Call) RunAndReturn(run func(conn types.Connection)) *MockConnectionManager_RemoveConnection_Call {
	_c.Run(run)
	return _c
}
