// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kubemock

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockSecretStore creates a new instance of MockSecretStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretStore {
	mock := &MockSecretStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretStore is an autogenerated mock type for the SecretStore type
type MockSecretStore struct {
	mock.Mock
}

type MockSecretStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretStore) EXPECT() *MockSecretStore_Expecter {
	return &MockSecretStore_Expecter{mock: &_m.Mock}
}

// GetSecretByName provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) GetSecretByName(name string) (*v1.Secret, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretByName")
	}

	var r0 *v1.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v1.Secret, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v1.Secret); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretStore_GetSecretByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretByName'
type MockSecretStore_GetSecretByName_Call struct {
	*mock.Call
}

// GetSecretByName is a helper method to define mock.On call
//   - name string
func (_e *MockSecretStore_Expecter) GetSecretByName(name interface{}) *MockSecretStore_GetSecretByName_Call {
	return &MockSecretStore_GetSecretByName_Call{Call: _e.mock.On("GetSecretByName", name)}
}

func (_c *MockSecretStore_GetSecretByName_Call) Run(run func(name string)) *MockSecretStore_GetSecretByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretStore_GetSecretByName_Call) Return(secret *v1.Secret, err error) *MockSecretStore_GetSecretByName_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretStore_GetSecretByName_Call) RunAndReturn(run func(name string) (*v1.Secret, error)) *MockSecretStore_GetSecretByName_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretStore_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSecretStore_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockSecretStore_Expecter) Run() *MockSecretStore_Run_Call {
	return &MockSecretStore_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockSecretStore_Run_Call) Run(run func()) *MockSecretStore_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSecretStore_Run_Call) Return(err error) *MockSecretStore_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretStore_Run_Call) RunAndReturn(run func() error) *MockSecretStore_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) Stop() {
	_mock.Called()
	return
}

// MockSecretStore_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockSecretStore_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockSecretStore_Expecter) Stop() *MockSecretStore_Stop_Call {
	return &MockSecretStore_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockSecretStore_Stop_Call) Run(run func()) *MockSecretStore_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSecretStore_Stop_Call) Return() *MockSecretStore_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSecretStore_Stop_Call) RunAndReturn(run func()) *MockSecretStore_Stop_Call {
	_c.Run(run)
	return _c
}
