// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kubemock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockConfigMapStore creates a new instance of MockConfigMapStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigMapStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigMapStore {
	mock := &MockConfigMapStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigMapStore is an autogenerated mock type for the ConfigMapStore type
type MockConfigMapStore struct {
	mock.Mock
}

type MockConfigMapStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigMapStore) EXPECT() *MockConfigMapStore_Expecter {
	return &MockConfigMapStore_Expecter{mock: &_m.Mock}
}

// CreateConfigMap provides a mock function for the type MockConfigMapStore
func (_mock *MockConfigMapStore) CreateConfigMap(ctx context.Context, namespace string, cm *v1.ConfigMap) error {
	ret := _mock.Called(ctx, namespace, cm)

	if len(ret) == 0 {
		panic("no return value specified for CreateConfigMap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.ConfigMap) error); ok {
		r0 = returnFunc(ctx, namespace, cm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigMapStore_CreateConfigMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConfigMap'
type MockConfigMapStore_CreateConfigMap_Call struct {
	*mock.Call
}

// CreateConfigMap is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - cm *v1.ConfigMap
func (_e *MockConfigMapStore_Expecter) CreateConfigMap(ctx interface{}, namespace interface{}, cm interface{}) *MockConfigMapStore_CreateConfigMap_Call {
	return &MockConfigMapStore_CreateConfigMap_Call{Call: _e.mock.On("CreateConfigMap", ctx, namespace, cm)}
}

func (_c *MockConfigMapStore_CreateConfigMap_Call) Run(run func(ctx context.Context, namespace string, cm *v1.ConfigMap)) *MockConfigMapStore_CreateConfigMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1.ConfigMap
		if args[2] != nil {
			arg2 = args[2].(*v1.ConfigMap)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigMapStore_CreateConfigMap_Call) Return(err error) *MockConfigMapStore_CreateConfigMap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigMapStore_CreateConfigMap_Call) RunAndReturn(run func(ctx context.Context, namespace string, cm *v1.ConfigMap) error) *MockConfigMapStore_CreateConfigMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigmapByNameAndNamespace provides a mock function for the type MockConfigMapStore
func (_mock *MockConfigMapStore) GetConfigmapByNameAndNamespace(name string, namespace string) (*v1.ConfigMap, error) {
	ret := _mock.Called(name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigmapByNameAndNamespace")
	}

	var r0 *v1.ConfigMap
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*v1.ConfigMap, error)); ok {
		return returnFunc(name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *v1.ConfigMap); ok {
		r0 = returnFunc(name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigMapStore_GetConfigmapByNameAndNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigmapByNameAndNamespace'
type MockConfigMapStore_GetConfigmapByNameAndNamespace_Call struct {
	*mock.Call
}

// GetConfigmapByNameAndNamespace is a helper method to define mock.On call
//   - name string
//   - namespace string
func (_e *MockConfigMapStore_Expecter) GetConfigmapByNameAndNamespace(name interface{}, namespace interface{}) *MockConfigMapStore_GetConfigmapByNameAndNamespace_Call {
	return &MockConfigMapStore_GetConfigmapByNameAndNamespace_Call{Call: _e.mock.On("GetConfigmapByNameAndNamespace", name, namespace)}
}

func (_c *MockConfigMapStore_GetConfigmapByNameAndNamespace_Call) Run(run func(name string, namespace string)) *MockConfigMapStore_GetConfigmapByNameAndNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigMapStore_GetConfigmapByNameAndNamespace_Call) Return(configMap *v1.ConfigMap, err error) *MockConfigMapStore_GetConfigmapByNameAndNamespace_Call {
	_c.Call.Return(configMap, err)
	return _c
}

func (_c *MockConfigMapStore_GetConfigmapByNameAndNamespace_Call) RunAndReturn(run func(name string, namespace string) (*v1.ConfigMap, error)) *MockConfigMapStore_GetConfigmapByNameAndNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockConfigMapStore
func (_mock *MockConfigMapStore) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigMapStore_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockConfigMapStore_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockConfigMapStore_Expecter) Run() *MockConfigMapStore_Run_Call {
	return &MockConfigMapStore_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockConfigMapStore_Run_Call) Run(run func()) *MockConfigMapStore_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigMapStore_Run_Call) Return(err error) *MockConfigMapStore_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigMapStore_Run_Call) RunAndReturn(run func() error) *MockConfigMapStore_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockConfigMapStore
func (_mock *MockConfigMapStore) Stop() {
	_mock.Called()
	return
}

// MockConfigMapStore_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockConfigMapStore_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockConfigMapStore_Expecter) Stop() *MockConfigMapStore_Stop_Call {
	return &MockConfigMapStore_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockConfigMapStore_Stop_Call) Run(run func()) *MockConfigMapStore_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigMapStore_Stop_Call) Return() *MockConfigMapStore_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigMapStore_Stop_Call) RunAndReturn(run func()) *MockConfigMapStore_Stop_Call {
	_c.Run(run)
	return _c
}

// UpdateConfigMap provides a mock function for the type MockConfigMapStore
func (_mock *MockConfigMapStore) UpdateConfigMap(ctx context.Context, namespace string, cm *v1.ConfigMap) error {
	ret := _mock.Called(ctx, namespace, cm)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfigMap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.ConfigMap) error); ok {
		r0 = returnFunc(ctx, namespace, cm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigMapStore_UpdateConfigMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConfigMap'
type MockConfigMapStore_UpdateConfigMap_Call struct {
	*mock.Call
}

// UpdateConfigMap is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - cm *v1.ConfigMap
func (_e *MockConfigMapStore_Expecter) UpdateConfigMap(ctx interface{}, namespace interface{}, cm interface{}) *MockConfigMapStore_UpdateConfigMap_Call {
	return &MockConfigMapStore_UpdateConfigMap_Call{Call: _e.mock.On("UpdateConfigMap", ctx, namespace, cm)}
}

func (_c *MockConfigMapStore_UpdateConfigMap_Call) Run(run func(ctx context.Context, namespace string, cm *v1.ConfigMap)) *MockConfigMapStore_UpdateConfigMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1.ConfigMap
		if args[2] != nil {
			arg2 = args[2].(*v1.ConfigMap)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigMapStore_UpdateConfigMap_Call) Return(err error) *MockConfigMapStore_UpdateConfigMap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigMapStore_UpdateConfigMap_Call) RunAndReturn(run func(ctx context.Context, namespace string, cm *v1.ConfigMap) error) *MockConfigMapStore_UpdateConfigMap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretStore creates a new instance of MockSecretStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretStore {
	mock := &MockSecretStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretStore is an autogenerated mock type for the SecretStore type
type MockSecretStore struct {
	mock.Mock
}

type MockSecretStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretStore) EXPECT() *MockSecretStore_Expecter {
	return &MockSecretStore_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) CreateSecret(ctx context.Context, namespace string, secret *v1.Secret) error {
	ret := _mock.Called(ctx, namespace, secret)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.Secret) error); ok {
		r0 = returnFunc(ctx, namespace, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretStore_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockSecretStore_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - secret *v1.Secret
func (_e *MockSecretStore_Expecter) CreateSecret(ctx interface{}, namespace interface{}, secret interface{}) *MockSecretStore_CreateSecret_Call {
	return &MockSecretStore_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, namespace, secret)}
}

func (_c *MockSecretStore_CreateSecret_Call) Run(run func(ctx context.Context, namespace string, secret *v1.Secret)) *MockSecretStore_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1.Secret
		if args[2] != nil {
			arg2 = args[2].(*v1.Secret)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretStore_CreateSecret_Call) Return(err error) *MockSecretStore_CreateSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretStore_CreateSecret_Call) RunAndReturn(run func(ctx context.Context, namespace string, secret *v1.Secret) error) *MockSecretStore_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretByNameAndNamespace provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) GetSecretByNameAndNamespace(name string, namespace string) (*v1.Secret, error) {
	ret := _mock.Called(name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretByNameAndNamespace")
	}

	var r0 *v1.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*v1.Secret, error)); ok {
		return returnFunc(name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *v1.Secret); ok {
		r0 = returnFunc(name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretStore_GetSecretByNameAndNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretByNameAndNamespace'
type MockSecretStore_GetSecretByNameAndNamespace_Call struct {
	*mock.Call
}

// GetSecretByNameAndNamespace is a helper method to define mock.On call
//   - name string
//   - namespace string
func (_e *MockSecretStore_Expecter) GetSecretByNameAndNamespace(name interface{}, namespace interface{}) *MockSecretStore_GetSecretByNameAndNamespace_Call {
	return &MockSecretStore_GetSecretByNameAndNamespace_Call{Call: _e.mock.On("GetSecretByNameAndNamespace", name, namespace)}
}

func (_c *MockSecretStore_GetSecretByNameAndNamespace_Call) Run(run func(name string, namespace string)) *MockSecretStore_GetSecretByNameAndNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretStore_GetSecretByNameAndNamespace_Call) Return(secret *v1.Secret, err error) *MockSecretStore_GetSecretByNameAndNamespace_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretStore_GetSecretByNameAndNamespace_Call) RunAndReturn(run func(name string, namespace string) (*v1.Secret, error)) *MockSecretStore_GetSecretByNameAndNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretStore_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSecretStore_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockSecretStore_Expecter) Run() *MockSecretStore_Run_Call {
	return &MockSecretStore_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockSecretStore_Run_Call) Run(run func()) *MockSecretStore_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSecretStore_Run_Call) Return(err error) *MockSecretStore_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretStore_Run_Call) RunAndReturn(run func() error) *MockSecretStore_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) Stop() {
	_mock.Called()
	return
}

// MockSecretStore_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockSecretStore_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockSecretStore_Expecter) Stop() *MockSecretStore_Stop_Call {
	return &MockSecretStore_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockSecretStore_Stop_Call) Run(run func()) *MockSecretStore_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSecretStore_Stop_Call) Return() *MockSecretStore_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSecretStore_Stop_Call) RunAndReturn(run func()) *MockSecretStore_Stop_Call {
	_c.Run(run)
	return _c
}

// UpdateSecret provides a mock function for the type MockSecretStore
func (_mock *MockSecretStore) UpdateSecret(ctx context.Context, namespace string, secret *v1.Secret) error {
	ret := _mock.Called(ctx, namespace, secret)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.Secret) error); ok {
		r0 = returnFunc(ctx, namespace, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretStore_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockSecretStore_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - secret *v1.Secret
func (_e *MockSecretStore_Expecter) UpdateSecret(ctx interface{}, namespace interface{}, secret interface{}) *MockSecretStore_UpdateSecret_Call {
	return &MockSecretStore_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, namespace, secret)}
}

func (_c *MockSecretStore_UpdateSecret_Call) Run(run func(ctx context.Context, namespace string, secret *v1.Secret)) *MockSecretStore_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1.Secret
		if args[2] != nil {
			arg2 = args[2].(*v1.Secret)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretStore_UpdateSecret_Call) Return(err error) *MockSecretStore_UpdateSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretStore_UpdateSecret_Call) RunAndReturn(run func(ctx context.Context, namespace string, secret *v1.Secret) error) *MockSecretStore_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}
